version: '2.2'

services:
  weblate:
    image: ${DOCKER_REGISTRY}/weblate:${TAG:-latest}
    links:
      - database
      - cache
    ports:
      - 80:80
    volumes:
      - weblate-data:/app/data
    env_file:
      - ./environment
    environment:
      - WEBLATE_ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: always
    depends_on:
      - database
      - cache

  database:
    image: postgres:9.6-alpine
    env_file:
      - ./environment
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  cache:
    image: memcached:1.5-alpine
    restart: always

volumes:
  weblate-data: {}
  postgres-data: {}
